/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocultivos;

import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class MenuOpcciones extends javax.swing.JFrame {

    /**
     * Creates new form MenuOpcciones
     */
    public MenuOpcciones() {
         this.setLocationRelativeTo(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCPanel1 = new com.bolivia.panel.JCPanel();
        rbtAntena = new javax.swing.JRadioButton();
        rbtPlanta = new javax.swing.JRadioButton();
        BTNCONTINUAR = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4), "SELECCIONE LA OPCCION \n A REALIZAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Engravers MT", 3, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jCPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuOpcciones.jpg"))); // NOI18N
        jCPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rbtAntena.setBackground(new java.awt.Color(0, 51, 204));
        rbtAntena.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        rbtAntena.setForeground(new java.awt.Color(255, 255, 255));
        rbtAntena.setText("ANTENA");
        jCPanel1.add(rbtAntena, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 170, 60));

        rbtPlanta.setBackground(new java.awt.Color(0, 51, 204));
        rbtPlanta.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        rbtPlanta.setForeground(new java.awt.Color(255, 255, 255));
        rbtPlanta.setText("PLANTA");
        rbtPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPlantaActionPerformed(evt);
            }
        });
        jCPanel1.add(rbtPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 170, 70));

        BTNCONTINUAR.setBackground(new java.awt.Color(0, 102, 204));
        BTNCONTINUAR.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        BTNCONTINUAR.setForeground(new java.awt.Color(255, 255, 255));
        BTNCONTINUAR.setText("CONTINUAR");
        BTNCONTINUAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCONTINUARActionPerformed(evt);
            }
        });
        jCPanel1.add(BTNCONTINUAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 210, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuOpcciones.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 80));

        jCPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 300, 80));

        jButton3.setBackground(new java.awt.Color(0, 51, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("REGRESAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jCPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 110, 40));

        getContentPane().add(jCPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 110, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCONTINUARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCONTINUARActionPerformed
              
        if (rbtPlanta.isSelected()){
             BTNMODIFICAR N = new BTNMODIFICAR();
            N.setVisible(true);
            dispose();
                
        }
        
        if(rbtAntena.isSelected()){
             Antenas Nk = new Antenas();
            Nk.setVisible(true);
            dispose();}
        
        
    }//GEN-LAST:event_BTNCONTINUARActionPerformed

    private void rbtPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPlantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtPlantaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Principal q = new Principal();
        q.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        Principal q = new Principal();
        q.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpcciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpcciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCONTINUAR;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.bolivia.panel.JCPanel jCPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtAntena;
    private javax.swing.JRadioButton rbtPlanta;
    // End of variables declaration//GEN-END:variables
}
