/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocultivos;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class MenuEliminar extends javax.swing.JFrame {

    /**
     * Creates new form MenuEliminar
     */
    public MenuEliminar() {
         this.setLocationRelativeTo(this);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCPanel1 = new com.bolivia.panel.JCPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbtANTENA = new javax.swing.JRadioButton();
        rbtPlanta1 = new javax.swing.JRadioButton();
        rbtZona = new javax.swing.JRadioButton();
        BTNCONTINUARm = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 18)), "SELECCIONE QUE DESEA ELIMINAR ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jCPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuOpcciones.jpg"))); // NOI18N
        jCPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/MenuOpcciones.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jCPanel1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 80, 70));

        rbtANTENA.setBackground(new java.awt.Color(0, 51, 204));
        rbtANTENA.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        rbtANTENA.setForeground(new java.awt.Color(255, 255, 255));
        rbtANTENA.setText("ANTENA");
        rbtANTENA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtANTENAActionPerformed(evt);
            }
        });
        jCPanel1.add(rbtANTENA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 140, 40));

        rbtPlanta1.setBackground(new java.awt.Color(0, 51, 204));
        rbtPlanta1.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        rbtPlanta1.setForeground(new java.awt.Color(255, 255, 255));
        rbtPlanta1.setText("PLANTA");
        rbtPlanta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtPlanta1ActionPerformed(evt);
            }
        });
        jCPanel1.add(rbtPlanta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 140, 40));

        rbtZona.setBackground(new java.awt.Color(0, 51, 204));
        rbtZona.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        rbtZona.setForeground(new java.awt.Color(255, 255, 255));
        rbtZona.setText("ZONA");
        jCPanel1.add(rbtZona, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 140, 40));

        BTNCONTINUARm.setBackground(new java.awt.Color(0, 102, 204));
        BTNCONTINUARm.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        BTNCONTINUARm.setForeground(new java.awt.Color(255, 255, 255));
        BTNCONTINUARm.setText("CONTINUAR");
        BTNCONTINUARm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCONTINUARmActionPerformed(evt);
            }
        });
        jCPanel1.add(BTNCONTINUARm, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 170, 50));

        jButton2.setBackground(new java.awt.Color(0, 51, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jCPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jCPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNCONTINUARmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCONTINUARmActionPerformed

        if (rbtPlanta1.isSelected())
        {
            btnEliminarRegistros i = new btnEliminarRegistros();
            i.setVisible(true);
            dispose();

        }

        if(rbtZona.isSelected())
        {
            EliminarZona Nk = new EliminarZona();
            Nk.setVisible(true);
            dispose();
        }
        
        if(rbtANTENA.isSelected())
        {
            eliminarPlanta Nk = new eliminarPlanta();
            Nk.setVisible(true);
            dispose();
        }

    }//GEN-LAST:event_BTNCONTINUARmActionPerformed

    private void rbtPlanta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtPlanta1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rbtPlanta1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Principal q = new Principal();
        q.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbtANTENAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtANTENAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtANTENAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCONTINUARm;
    private javax.swing.JButton jButton2;
    private com.bolivia.panel.JCPanel jCPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtANTENA;
    private javax.swing.JRadioButton rbtPlanta1;
    private javax.swing.JRadioButton rbtZona;
    // End of variables declaration//GEN-END:variables
}
