/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectocultivos;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rojerusan.RSPanelsSlider;
import java.awt.*;
import org.json.simple.JSONObject;
/**
 *
 * @author RojeruSan
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        // metodos para la tabla de zonas 
        this.tabla.setModel(modelo);
        this.modelo.addColumn("Longitud");
        this.modelo.addColumn("Nombre Zona");
        this.modelo.addColumn("Latitud");
         
         // tabla plantas 
          this.tablaplatas1.setModel(modelop);
          this.modelop.addColumn("Nombre De La Planta");
                  
          
         // tabla antenas
         
         this.tablaantenas.setModel(modelopA);
         this.modelopA.addColumn("ID ZONA");
          this.modelopA.addColumn("RECEPCION");
         
         
         
          
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BTN10 = new javax.swing.JButton();
        BTN11 = new javax.swing.JButton();
        BTN12 = new javax.swing.JButton();
        BTN13 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        pnl1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtlongitud = new javax.swing.JTextField();
        zonanombre = new javax.swing.JLabel();
        txtnombrezona = new javax.swing.JTextField();
        Latitud = new javax.swing.JLabel();
        txtlatitud = new javax.swing.JTextField();
        btmAgregar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        NomPlanta = new javax.swing.JLabel();
        txtplantaagre = new javax.swing.JTextField();
        agregarplanta = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaplatas1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnagregarantenas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtidzonaantena = new javax.swing.JTextField();
        txtrecepcion = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaantenas = new javax.swing.JTable();
        pnl3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCPanel1 = new com.bolivia.panel.JCPanel();
        jLabel6 = new javax.swing.JLabel();
        nomplanta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        idzona = new javax.swing.JTextField();
        consulta = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        mostrar = new javax.swing.JTextArea();
        todas = new javax.swing.JButton();
        UR = new javax.swing.JButton();
        pnl4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jCPanel2 = new com.bolivia.panel.JCPanel();
        jLabel7 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTN10.setBackground(new java.awt.Color(0, 102, 204));
        BTN10.setForeground(new java.awt.Color(255, 255, 255));
        BTN10.setText("HERRAMIENTAS");
        BTN10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN10ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 210, 70));

        BTN11.setBackground(new java.awt.Color(0, 102, 204));
        BTN11.setForeground(new java.awt.Color(255, 255, 255));
        BTN11.setText("Insertar");
        BTN11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN11ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 210, 70));

        BTN12.setBackground(new java.awt.Color(0, 102, 204));
        BTN12.setForeground(new java.awt.Color(255, 255, 255));
        BTN12.setText("Consultar Datos");
        BTN12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN12ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 210, 70));

        BTN13.setBackground(new java.awt.Color(0, 102, 204));
        BTN13.setForeground(new java.awt.Color(255, 255, 255));
        BTN13.setText("Modificar /Eliminar");
        BTN13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN13ActionPerformed(evt);
            }
        });
        jPanel2.add(BTN13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 210, 70));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/trabalhador-agricultor_1325-134.jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, 120));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 545));

        rSPanelsSlider1.setBackground(new java.awt.Color(255, 255, 255));

        pnl1.setBackground(new java.awt.Color(0, 102, 255));
        pnl1.setName("pnl1"); // NOI18N
        pnl1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Maintenance_96px.png"))); // NOI18N
        jLabel1.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel1MouseMoved(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        pnl1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 130, 130));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 102, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Google_Drive_96px.png"))); // NOI18N
        jLabel11.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel11.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel11MouseMoved(evt);
            }
        });
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        pnl1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 130, 130));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 204));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Idea_96px.png"))); // NOI18N
        jLabel12.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel12.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel12MouseMoved(evt);
            }
        });
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel12MouseExited(evt);
            }
        });
        pnl1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 130, 130));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 204));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Handshake_96px.png"))); // NOI18N
        jLabel13.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel13.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel13MouseMoved(evt);
            }
        });
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel13MouseExited(evt);
            }
        });
        pnl1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 130, 130));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 102, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Clock_96px.png"))); // NOI18N
        jLabel14.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel14MouseMoved(evt);
            }
        });
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        pnl1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, 130));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 102, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8_Today_96px.png"))); // NOI18N
        jLabel15.setBorder(new org.jdesktop.swingx.border.DropShadowBorder());
        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLabel15MouseMoved(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        pnl1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 130, 130));

        rSPanelsSlider1.add(pnl1, "card2");

        pnl2.setBackground(new java.awt.Color(204, 255, 255));
        pnl2.setName("pnl2"); // NOI18N
        pnl2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Zona Cultivo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 3, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Longitud:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 36, -1, -1));
        jPanel3.add(txtlongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 32, 111, -1));

        zonanombre.setText("Nombre de La Zona:");
        jPanel3.add(zonanombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 78, -1, -1));
        jPanel3.add(txtnombrezona, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 82, 111, -1));

        Latitud.setText("Latitud:");
        jPanel3.add(Latitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 131, -1, -1));
        jPanel3.add(txtlatitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 131, 111, -1));

        btmAgregar.setText("AGREGAR");
        btmAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(btmAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 90, -1));

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 90, -1));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabla);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 440, 90));

        pnl2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 460, 337));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Plantas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Curlz MT", 3, 24), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomPlanta.setText("Nombre De La Planta");
        jPanel5.add(NomPlanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        jPanel5.add(txtplantaagre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 120, -1));

        agregarplanta.setText("Agregar");
        agregarplanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarplantaActionPerformed(evt);
            }
        });
        jPanel5.add(agregarplanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 100, 30));

        tablaplatas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaplatas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaplatas1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaplatas1);

        jPanel5.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 171, 270, 100));

        pnl2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 15, 293, 282));

        jPanel7.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnl2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 343, 774, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ANTENAS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnagregarantenas.setText("agregar");
        btnagregarantenas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarantenasActionPerformed(evt);
            }
        });
        jPanel6.add(btnagregarantenas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 77, 89, 33));

        jLabel4.setText("ID ZONA");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 69, -1, -1));

        jLabel9.setText("RECEPCION");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 110, -1, -1));
        jPanel6.add(txtidzonaantena, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 60, 105, 35));
        jPanel6.add(txtrecepcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 101, 99, 34));

        tablaantenas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaantenas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaantenasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaantenas);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 280, 70));

        pnl2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 300, 240));

        rSPanelsSlider1.add(pnl2, "card3");

        pnl3.setBackground(new java.awt.Color(255, 255, 255));
        pnl3.setName("pnl3"); // NOI18N
        pnl3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 51, 204));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONSULTAS");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnl3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));

        jCPanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/plantaNombre.jpg"))); // NOI18N
        jCPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Nombre De La Planta");
        jCPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        nomplanta.setBackground(new java.awt.Color(255, 255, 255));
        jCPanel1.add(nomplanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 168, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID ZONA");
        jCPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        idzona.setBackground(new java.awt.Color(255, 255, 255));
        jCPanel1.add(idzona, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 168, 39));

        consulta.setBackground(new java.awt.Color(0, 0, 153));
        consulta.setForeground(new java.awt.Color(0, 0, 255));
        consulta.setText("CONSULTAR");
        consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaActionPerformed(evt);
            }
        });
        jCPanel1.add(consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 141, 47));

        mostrar.setBackground(new java.awt.Color(255, 255, 255));
        mostrar.setColumns(20);
        mostrar.setRows(5);
        jScrollPane5.setViewportView(mostrar);

        jCPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 440, 140));

        todas.setText("TODAS LAS PLANTAS");
        todas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todasActionPerformed(evt);
            }
        });
        jCPanel1.add(todas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));

        UR.setText("Ultimo Registro");
        UR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                URActionPerformed(evt);
            }
        });
        jCPanel1.add(UR, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, -1, -1));

        pnl3.add(jCPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 780, 420));

        rSPanelsSlider1.add(pnl3, "card4");

        pnl4.setBackground(new java.awt.Color(255, 255, 255));
        pnl4.setName("pnl4"); // NOI18N
        pnl4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 790, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        pnl4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 70));

        jCPanel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cultivos-tierras.jpg"))); // NOI18N
        jCPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Footlight MT Light", 3, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("QUE DESEA REALIZAR ?");
        jCPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 6, -1, -1));

        btnModificar.setBackground(new java.awt.Color(0, 51, 153));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR REGISTROS");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jCPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 210, 70));

        btnEliminar.setBackground(new java.awt.Color(0, 0, 204));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR REGISTROS");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jCPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 70));

        pnl4.add(jCPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 780, 470));

        rSPanelsSlider1.add(pnl4, "card5");

        jPanel1.add(rSPanelsSlider1, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 0, 793, 545));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    DefaultTableModel modelo=new DefaultTableModel();
    
    DefaultTableModel modelop=new DefaultTableModel();
    
    DefaultTableModel modelopA=new DefaultTableModel();
    
    private void BTN10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN10ActionPerformed
        // TODO add your handling code here:
        if(!this. BTN10.isSelected()){
            this. BTN10.setSelected(true);
            this. BTN11.setSelected(false);
            this.BTN12.setSelected(false);
            this.BTN13.setSelected(false);
            
            rSPanelsSlider1.slidPanel(20, pnl1, RSPanelsSlider.direct.Right);
        }
    }//GEN-LAST:event_BTN10ActionPerformed

    private void BTN11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN11ActionPerformed
        // TODO add your handling code here:
          if(!this. BTN11.isSelected()){
            this.BTN10.setSelected(false);
            this. BTN11.setSelected(true);
            this.BTN12.setSelected(false);
            this.BTN13.setSelected(false);
            
            rSPanelsSlider1.slidPanel(20, pnl2, RSPanelsSlider.direct.Right);
        }
    }//GEN-LAST:event_BTN11ActionPerformed

    private void BTN12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN12ActionPerformed
        // TODO add your handling code here:
        
         if(!this.BTN12.isSelected()){
            this.BTN10.setSelected(false);
            this. BTN11.setSelected(false);
            this.BTN12.setSelected(true);
            this.BTN13.setSelected(false);
            
            rSPanelsSlider1.slidPanel(20, pnl3, RSPanelsSlider.direct.Right);
        }
         
    }//GEN-LAST:event_BTN12ActionPerformed

    private void BTN13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN13ActionPerformed
        // TODO add your handling code here:
             if(!this.BTN13.isSelected()){
            this.BTN10.setSelected(false);
            this. BTN11.setSelected(false);
            this.BTN12.setSelected(false);
            this.BTN13.setSelected(true);
            
            rSPanelsSlider1.slidPanel(20, pnl4, RSPanelsSlider.direct.Right);
        }
    }//GEN-LAST:event_BTN13ActionPerformed

    private void btmAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAgregarActionPerformed
    
         this.modelo.addRow(new Object[]{
          this.txtlongitud.getText(),
          this.txtnombrezona.getText(), 
          this.txtlatitud.getText()});
         
      String a=txtlongitud.getText();
      String b=txtnombrezona.getText();
      String c=txtlatitud.getText();
      if (txtlongitud.getText().isEmpty()  || txtnombrezona.getText().isEmpty() || txtlatitud.getText().isEmpty()
              ){
          JOptionPane.showMessageDialog(this, "Favor De No dejar campos vacios  ");
          
          
      }
      
      
      
  
      
String solicitud_url = "http://127.0.0.1/esp32/public/api/zonas";
        curl api = new curl(solicitud_url, "POST");
        
        JSONObject sembradio = new JSONObject();
        //sembradio.put("nomplanta", "Camote");
        sembradio.put("longitud",a);
        sembradio.put("NomZona",b);
        sembradio.put("Latitud",c);
        
        JSONObject obj = api.apicall(sembradio); 
        System.out.println(obj.get("mensaje"));
        
        
      this.txtlongitud.setText("");
      this.txtnombrezona.setText("");
      this.txtlatitud.setText("");

          
    }//GEN-LAST:event_btmAgregarActionPerformed

    int filas;
    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
 
        int fila_seleccionada=tabla.getSelectedRow();
        if(fila_seleccionada>=0){
            modelo.removeRow(fila_seleccionada);
            
        }else{
            
            JOptionPane.showMessageDialog(null, "seleccione una fila por favor ");
            
        }
       
    }//GEN-LAST:event_btneliminarActionPerformed

    
    private void agregarplantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarplantaActionPerformed
        // TODO add your handling code here:
     
             //almacenan a la tabla 
               this.modelop.addRow(new Object[]{
               this.txtplantaagre.getText()});
               
               String a=txtplantaagre.getText();
     
          if (txtplantaagre.getText().equals("")) {
          javax.swing.JOptionPane.showMessageDialog(this, "llenar los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
          txtplantaagre.requestFocus();
          }
          else 
          {
           
String solicitud_url = "http://127.0.0.1/esp32/public/api/cultivos";
        curl api = new curl(solicitud_url, "POST");
        
        JSONObject sembradio = new JSONObject();
        sembradio.put("nomplanta", a);
        
        JSONObject obj = api.apicall(sembradio); 
        System.out.println(obj.get("mensaje"));
        
         this.txtplantaagre.setText("");
          
          }
        
    }//GEN-LAST:event_agregarplantaActionPerformed

    private void jLabel14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseMoved
        // TODO add your handling code here:
         jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153) ) );
         
    }//GEN-LAST:event_jLabel14MouseMoved

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
         jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255) ) );
    }//GEN-LAST:event_jLabel14MouseExited

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        int fila_seleccionada=tabla.getSelectedRow();
        txtlongitud.setText(tabla.getValueAt(fila_seleccionada, 0).toString());
        txtnombrezona.setText(tabla.getValueAt(fila_seleccionada, 1).toString());
        txtlatitud.setText(tabla.getValueAt(fila_seleccionada, 2).toString());
        
        filas=fila_seleccionada;
    }//GEN-LAST:event_tablaMouseClicked

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255) ) );
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255) ) );
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel12MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseExited
        // TODO add your handling code here:
         jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255) ) );
    }//GEN-LAST:event_jLabel12MouseExited

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
          jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255) ) );
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel13MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseExited
        // TODO add your handling code here:
          jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255) ) );
    }//GEN-LAST:event_jLabel13MouseExited

    private void jLabel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseMoved
        // TODO add your handling code here:
         jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153) ) );
    }//GEN-LAST:event_jLabel1MouseMoved

    private void jLabel11MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseMoved
        // TODO add your handling code here:
         jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153) ) );
    }//GEN-LAST:event_jLabel11MouseMoved

    private void jLabel12MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseMoved
        // TODO add your handling code here:
         jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153) ) );
    }//GEN-LAST:event_jLabel12MouseMoved

    private void jLabel15MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseMoved
        // TODO add your handling code here:
         jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153) ) );
    }//GEN-LAST:event_jLabel15MouseMoved

    private void jLabel13MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseMoved
        // TODO add your handling code here:
         jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153) ) );
    }//GEN-LAST:event_jLabel13MouseMoved

    private void btnagregarantenasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarantenasActionPerformed
        // TODO add your handling code here:
        this.modelopA.addRow(new Object[]{
               this.txtidzonaantena.getText(),
                 this.txtrecepcion.getText()
         });
        String a=txtidzonaantena.getText();
             String b=txtrecepcion.getText();
             
           this.txtidzonaantena.setText("");
           this.txtrecepcion.setText("");
           
String solicitud_url = "http://127.0.0.1/esp32/public/api/antenas";
        curl api = new curl(solicitud_url, "POST");
        
        JSONObject sembradio = new JSONObject();
        sembradio.put("idZona", a);
        sembradio.put("Recepcion", b);
        
        JSONObject obj = api.apicall(sembradio); 
        System.out.println(obj.get("mensaje"));
        
      
    }//GEN-LAST:event_btnagregarantenasActionPerformed

    private void tablaplatas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaplatas1MouseClicked
        // TODO add your handling code here:
          int fila_seleccionadaplanta=tabla.getSelectedRow();
        txtplantaagre.setText(tablaplatas1.getValueAt(fila_seleccionadaplanta, 0).toString());

        filas=fila_seleccionadaplanta;
        
    }//GEN-LAST:event_tablaplatas1MouseClicked

    private void tablaantenasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaantenasMouseClicked
        // TODO add your handling code here:
        int fila_seleccionadaantena=tabla.getSelectedRow();
        
        txtidzonaantena.setText(tabla.getValueAt(fila_seleccionadaantena, 0).toString());
        txtrecepcion.setText(tabla.getValueAt(fila_seleccionadaantena, 0).toString());

        filas=fila_seleccionadaantena;
    }//GEN-LAST:event_tablaantenasMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        
         MenuOpcciones JN = new MenuOpcciones();
            JN.setVisible(true);
            dispose();

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
               MenuEliminar JN = new MenuEliminar();
            JN.setVisible(true);
            dispose();

        
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaActionPerformed
        // TODO add your handling code here:
            String n=nomplanta.getText();
            String z=idzona.getText();
           this.nomplanta.setText("");
           this.idzona.setText("");
           
String solicitud_url = "http://127.0.0.1/esp32/public/api/postconsulta";
        curl api = new curl(solicitud_url, "POST");
        
        JSONObject BTNGET = new JSONObject();
        BTNGET.put("NomPlanta", n);
        BTNGET.put("idZona", z);
        
        JSONObject obj = api.apicall(BTNGET); 
        System.out.println(obj.get("Nombre"));
        System.out.println(obj.get("result"));
        String a=obj.toString();
        this.mostrar.setText(a);
    }//GEN-LAST:event_consultaActionPerformed

    private void todasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todasActionPerformed
        // TODO add your handling code here:
        String solicitud_url = "http://127.0.0.1/esp32/public/api/registro";
        curl api = new curl(solicitud_url, "PUT");
        
        JSONObject BTNGET = new JSONObject();
        
        JSONObject obj = api.apicall(BTNGET); 
        System.out.println(obj.get("result"));
        String a=obj.toString();
        this.mostrar.setText(a);
    }//GEN-LAST:event_todasActionPerformed

    private void URActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_URActionPerformed
        // TODO add your handling code here:
        String solicitud_url = "http://127.0.0.1/esp32/public/api/plantazona";
        curl api = new curl(solicitud_url, "PUT");
        
        JSONObject BTNGET = new JSONObject();
        
        JSONObject obj = api.apicall(BTNGET); 
        System.out.println(obj.get("result"));
        String a=obj.toString();
        this.mostrar.setText(a);
    }//GEN-LAST:event_URActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN10;
    private javax.swing.JButton BTN11;
    private javax.swing.JButton BTN12;
    private javax.swing.JButton BTN13;
    private javax.swing.JLabel Latitud;
    private javax.swing.JLabel NomPlanta;
    private javax.swing.JButton UR;
    private javax.swing.JButton agregarplanta;
    private javax.swing.JButton btmAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnagregarantenas;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton consulta;
    private javax.swing.JTextField idzona;
    private com.bolivia.panel.JCPanel jCPanel1;
    private com.bolivia.panel.JCPanel jCPanel2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea mostrar;
    private javax.swing.JTextField nomplanta;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JTable tabla;
    private javax.swing.JTable tablaantenas;
    private javax.swing.JTable tablaplatas1;
    private javax.swing.JButton todas;
    private javax.swing.JTextField txtidzonaantena;
    private javax.swing.JTextField txtlatitud;
    private javax.swing.JTextField txtlongitud;
    private javax.swing.JTextField txtnombrezona;
    private javax.swing.JTextField txtplantaagre;
    private javax.swing.JTextField txtrecepcion;
    private javax.swing.JLabel zonanombre;
    // End of variables declaration//GEN-END:variables
}
